config/routes.rb
Proconfie3::Application.routes.draw do

  get "main/index"
  get "main/autocomplete"
  post "main/search"

  resources :empresas, :only => [:show]
  resources :categorias, :only => [:show]
  resources :reclamacoes, :only => [:index]

  root :to => 'main#index'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

  self.primary_key = 'categoria_id'
  
  has_many :empresas
  has_many :reclamacoes

  attr_accessible :categoria_id, :descricao
  
  # Categoria.search
  def self.search(query)
    categorias = []
    unless query.empty?
      q = "%#{query}%"
      categorias = self.where("descricao like ?", q).limit(10)
    end
    categorias
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  def show
    @categoria = Categoria.find(params[:id])
    estado = sigla_session.estado
    if estado.is_brasil?
      @empresas = @categoria.empresas.order("score DESC")
    else
      @empresas = estado.empresas.where("categoria_id = ?", @categoria.id).order("score DESC")
    end
  end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/show.html.erb
<% content_for :title, "Proconfie - #{@categoria.descricao}" %>

<% content_for :head do %>
  <%= stylesheet_link_tag 'categorias' %>
<% end %>

<div class="row">
  <div class="ten columns">
    <h2><%= @categoria.descricao %></h2>
  </div>
  <div class="two columns">
    <h2>Risco</h2>
  </div>
  <hr />
</div>
<div class="row">
  <% @empresas.each do |empresa| %>
    <div class="ten columns">
      <h4><%= link_to "#{empresa.nome}", empresa_path(empresa) %></h4>
    </div>
    <div class="two columns">
      <h4 class="<%= risco(empresa.score) %> has-tip tip-right" title="<%= empresa.score.to_i %>"><%= risco_header(empresa.score) %></h4>
    </div>
    </hr />
  <% end %>
</div>