config/routes.rb
Proconfie3::Application.routes.draw do

  get "main/index"
  get "main/autocomplete"
  post "main/search"

  resources :empresas, :only => [:show]
  resources :categorias, :only => [:show]
  resources :reclamacoes, :only => [:index]

  root :to => 'main#index'

end

app/models/empresa.rb
#!/bin/env ruby
# encoding: utf-8

class Empresa < ActiveRecord::Base

  self.primary_key = 'cnpj'
  
  belongs_to :radical_cnpj
  belongs_to :categoria
  has_many :reclamacoes
  has_many :problemas, :through => :reclamacoes
  belongs_to :estado

  attr_accessible :cnpj, :categoria_id, :radical_cnpj_id, :razao_social, :nome_fantasia,
                  :reclamacoes_menos_infinito_ate_tres_anos,
                  :reclamacoes_dois_anos_ate_tres_anos,
                  :reclamacoes_um_ano_ate_dois_anos,
                  :reclamacoes_seis_meses_ate_um_ano,
                  :reclamacoes_hoje_ate_seis_meses,
                  :percentual_reclamacoes_categoria_menos_infinito_ate_tres_anos,
                  :percentual_reclamacoes_categoria_dois_anos_ate_tres_anos,
                  :percentual_reclamacoes_categoria_um_ano_ate_dois_anos,
                  :percentual_reclamacoes_categoria_seis_meses_ate_um_ano, 
                  :percentual_reclamacoes_categoria_hoje_ate_seis_meses,
                  :slope_pedro,
                  :numero_normalizado_reclamacoes_categoria,
                  :mediana_duracao_reclamacoes,
                  :media_duracao_reclamacoes,
                  :skewness_duracao_reclamacoes,
                  :data_primeira_reclamacao,
                  :total_reclamacoes_resolvidas,
                  :numero_proporcional_reclamacoes_res_hoje_ate_seis_meses,
                  :numero_proporcional_reclamacoes_res_seis_meses_ate_um_ano,
                  :numero_proporcional_reclamacoes_res_um_ano_ate_dois_anos,
                  :numero_proporcional_reclamacoes_res_dois_anos_ate_tres_anos,
                  :slope_pes,
                  :score,
                  :estado_id
                  
  TIMESTAMPS = %w{2009-01 2010-01 2011-01 2011-06 2011-12}

  # To be used as empresa.nome (where empresa is an instance of Empresa)
  # Oftenly one of those attributes will be "NULL", but not both
  def nome
    nome = self.nome_fantasia
    nome = self.razao_social if nome == "NULL"
    nome
  end
  
  def ranking(estado)
    empresas = find_other_empresas_within_same_category(estado)
    empresas.index(self) + 1
  end
    
  # To be used as Empresa.search
  def self.search(query, estado)
    empresas = []
    unless query.empty?
      q = "%#{query}%"
      if estado.sigla == "BR"
        empresas = self.where("razao_social like ? or nome_fantasia like ?", q, q).limit(10)
      else
        empresas = estado.empresas.where("razao_social like ? or nome_fantasia like ?", q, q).limit(10)
      end
    end
    empresas
  end
  
  def find_other_empresas_within_same_category(estado)
    if estado.is_brasil?
      empresas = self.categoria.empresas.order("score DESC")
    else
      empresas = estado.empresas.where("categoria_id = ?", self.categoria.id).order("score DESC")
    end
  end
  
  def json_percentual_reclamacoes_resolvidas
    resolvidas = (self.total_reclamacoes_resolvidas / self.reclamacoes.size.to_f) * 100
    nao_resolvidas = 100 - resolvidas
    # Mostra os valores com apenas um digito significativo
    dados = [{:label => "Resolvidas", :value => Float("%.1g" % resolvidas)}, {:label => "Não resolvidas", :value => Float("%.1g" % nao_resolvidas)}]
    dados.to_json
  end
  
  def json_reclamacoes
    percentuais = [ self.reclamacoes_menos_infinito_ate_tres_anos, self.reclamacoes_dois_anos_ate_tres_anos,
                    self.reclamacoes_um_ano_ate_dois_anos, self.reclamacoes_seis_meses_ate_um_ano,
                    self.reclamacoes_hoje_ate_seis_meses]
    dados = []
    TIMESTAMPS.zip(percentuais).each do |timestamp, percentual|
      dados << {:time => timestamp, :value => percentual}
    end
    dados.to_json
  end
  
  def json_percentual_reclamacoes_categoria
    percentuais = [self.percentual_reclamacoes_categoria_menos_infinito_ate_tres_anos,
                   self.percentual_reclamacoes_categoria_dois_anos_ate_tres_anos,
                   self.percentual_reclamacoes_categoria_um_ano_ate_dois_anos,
                   self.percentual_reclamacoes_categoria_seis_meses_ate_um_ano, 
                   self.percentual_reclamacoes_categoria_hoje_ate_seis_meses]
    dados =[]
    TIMESTAMPS.zip(percentuais).each do |timestamp, percentual|
      dados << {:time => timestamp, :value => percentual * 100}
    end
    dados.to_json
  end
  
  def json_numero_proporcional_reclamacoes_resolvidas
    numeros = [self.numero_proporcional_reclamacoes_res_dois_anos_ate_tres_anos,
               self.numero_proporcional_reclamacoes_res_um_ano_ate_dois_anos,
               self.numero_proporcional_reclamacoes_res_seis_meses_ate_um_ano,
               self.numero_proporcional_reclamacoes_res_hoje_ate_seis_meses]
    dados =[]
    TIMESTAMPS[1..-1].zip(numeros).each do |timestamp, numero|
      dados << {:time => timestamp, :value => numero * 100}
    end
    dados.to_json
  end
  
  def json_problemas
    frequencias = Hash.new(0)
    self.problemas.each { |problema| frequencias[problema.descricao] += 1 }
    dados = []
    frequencias.sort_by {|k,v| v}.reverse.each do |problema, frequencia|    # ordered by frequency, decreasing
      dados << {:problem => problema, :frequency => frequencia}
    end
    dados.to_json
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  def show
    @empresa = Empresa.find(params[:id])
    @percentual_reclamacoes_resolvidas = @empresa.json_percentual_reclamacoes_resolvidas
    @reclamacoes = @empresa.json_reclamacoes
    @percentual_reclamacoes_categoria = @empresa.json_percentual_reclamacoes_categoria
    @proporcional_reclamacoes_resolvidas = @empresa.json_numero_proporcional_reclamacoes_resolvidas
    @problemas = @empresa.json_problemas
    @empresas_with_same_category = @empresa.find_other_empresas_within_same_category(sigla_session.estado)
  end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/show.html.erb
<% content_for :title, "Proconfie - #{@empresa.nome}" %>

<% content_for :head do %>

  <%= stylesheet_link_tag 'empresas' %>
  
  <script type="text/javascript">
    function plotDonut(elemento, dados) {
      Morris.Donut({
        element: elemento,
        data: dados,
        colors: ["#0b62a4", "#c60f13"],
        formatter: function (x) { return x + '%' } // 100 => 100%
      });
    }
    
    function plotLine(elemento, dados) {
      Morris.Line({
        element: elemento,
        data: dados,
        xkey: 'time',
        ykeys: ['value'],
        labels: ['Percentual']
      });
    }
    
    function plotLineReclamacoes(elemento, dados) {
      Morris.Line({
        element: elemento,
        data: dados,
        xkey: 'time',
        ykeys: ['value'],
        labels: ['Número de reclamações']
      });
    }
    
    function plotLineProporcional(elemento, dados) {
      Morris.Line({
        element: elemento,
        data: dados,
        xkey: 'time',
        ykeys: ['value'],
        labels: ['Valor']
      });
    }
    
    function plotBar(elemento, dados) {
      Morris.Bar({
        element: elemento,
        data: dados,
        xkey: 'problem',
        ykeys: ['frequency'],
        labels: ['Frequência']
      });
    }
    
    $(document).ready(function() {
      dados = <%= @percentual_reclamacoes_resolvidas.html_safe %>
      plotDonut("percentual_reclamacoes_resolvidas", dados);
      
      dados = <%= @reclamacoes.html_safe %>
      plotLineReclamacoes("reclamacoes", dados);
      
      dados = <%= @percentual_reclamacoes_categoria.html_safe %>
      plotLine("percentual_reclamacoes_categoria", dados);
      
      dados = <%= @proporcional_reclamacoes_resolvidas.html_safe %>
      plotLineProporcional("proporcional_reclamacoes_resolvidas", dados);
      
      dados = <%= @problemas.html_safe %>
      plotBar("problemas", dados);
      
      // Setting it directly using CSS (empresas.css) is hanging the browser!
      $('#graficos').css({'display':'none'});
      
    });
    
  </script>
<% end %>

<div class="row">
  <div class="twelve mobile-four columns">
    <h2><%= @empresa.nome %></h2>
  </div>
  <hr />
</div>

<div class="row">
  <div class="six mobile-four columns">
    <div class="panel">
      <h4 class="<%= risco(@empresa.score) %> has-tip tip-top" title="O risco da empresa é calculado é um valor entre 1 e 10 e é calculado a partir de 3 fatores:<br />(1) a proporção de reclamações que recebe dentro da sua categoria<br />(2) a proporção de reclamações resolvidas<br />(3) a tendência para receber mais ou menos reclamações ao longo do tempo">Risco: <%= risco_header(@empresa.score) %> (<%= @empresa.score.to_i %>)</h4>
      <h5 class="subheader">A <%= ranking(@empresa) %> <strong>pior</strong> no ramo, de um total de <%= @empresas_with_same_category.size %> empresas registradas</h5>
      <hr/>
      <ul class="circle">
        <li>Empresa do ramo de <%= link_to "#{@empresa.categoria.descricao}", categoria_path(@empresa.categoria) %></li>
        <li>A primeira reclamação registrado contra ela foi em <%= l(@empresa.data_primeira_reclamacao, :format => "%d/%m/%Y") %></li>
        <li><%= link_to_function "Saiba mais", "$('#graficos').toggle()" %> detalhes sobre esta empresa vendo gráficos.</li>
      </ul>
    </div>
  </div>
  <div class="six mobile-four columns">
    <div id="percentual_reclamacoes_resolvidas"></div>
    <div class="panel">
      <p>As reclamações não resolvidas contribuem para aumentar o risco de fazer negócios com uma determinada empresa. Ou seja, quanto maior a percentagem de reclamações não resolvidas contra uma empresa, maior também pode ser o risco de fazer negócios com ela.</p>
    </div>
  </div>  
</div>

<div id="graficos">

  <div class="row">
    <div class="six mobile-four columns">
      <div id="reclamacoes"></div>
      <div class="panel">
        <p>Esse gráfico mostra o número de reclamações obtidas por uma empresa ao longo dos anos. Um elevado número de reclamações não necessariamente significa que a empresa possui “alto risco”, ou seja, maior chance de gerar reclamações por usuários. Essa é uma informação importante na avaliação de empresas, mas para avaliar o risco de uma empresa com maior justiça é preciso considerar também outras informações, como as mostradas nos outros gráficos desta página.</p>
      </div>
    </div>
  
    <div class="six mobile-four columns">
      <div id="percentual_reclamacoes_categoria"></div>
      <div class="panel">
        <p>Esse gráfico mostra a percentagem do número de reclamações de uma empresa em relação a todas as reclamações da sua categoria. Essa informação é interessante, pois possibilita avaliar, de forma geral, o desempenho de uma determinada empresa em determinada categoria.</p>
      </div>
    </div>
  </div>

  <div class="row">
  
    <div class="six mobile-four columns">
      <div id="proporcional_reclamacoes_resolvidas"></div>
      <div class="panel">
        <p>Esse gráfico mostra a percentagem de reclamações resolvidas ao longo dos anos. O crescimento desse valor ao longo do tempo indica que a empresa está apresentando bom desempenho na resolução de problemas. Observe que esse valor percentual não é necessariamente proporcional ao número de reclamações. Isso significa que uma empresa pode apresentar um número de reclamações menor ao longo dos anos, mas diminuir o número de reclamações resolvidas. Essa é uma informação fundamental na criação do ranking de piores empresas em uma determinada categoria.</p>
      </div>
    </div>
    
    <div class="six mobile-four columns">
      <div id="problemas"></div>
      <div class="panel">
        <p>Esse gráfico mostra os cinco tipos de problemas mais comuns para uma determinada empresa, possibilitando uma visão geral dos mesmos. Essa informação também pode ser útil no processo de decisão de escolha de uma determinada empresa. Por exemplo, sendo considerada como um critério de desempate.</p>
      </div>
    </div>
    
  </div>
</div>